# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/todo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10proto/todo.proto\x12\x04todo"3\n\x04Todo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08"4\n\x11\x43reateTodoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08".\n\x12\x43reateTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo"\x1d\n\x0fReadTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x04",\n\x10ReadTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo"@\n\x11UpdateTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08".\n\x12UpdateTodoResponse\x12\x18\n\x04todo\x18\x01 \x01(\x0b\x32\n.todo.Todo"\x1f\n\x11\x44\x65leteTodoRequest\x12\n\n\x02id\x18\x01 \x01(\x04"%\n\x12\x44\x65leteTodoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08"\x12\n\x10ListTodosRequest".\n\x11ListTodosResponse\x12\x19\n\x05todos\x18\x01 \x03(\x0b\x32\n.todo.Todo2\xc9\x02\n\x0bTodoService\x12?\n\nCreateTodo\x12\x17.todo.CreateTodoRequest\x1a\x18.todo.CreateTodoResponse\x12\x39\n\x08ReadTodo\x12\x15.todo.ReadTodoRequest\x1a\x16.todo.ReadTodoResponse\x12?\n\nUpdateTodo\x12\x17.todo.UpdateTodoRequest\x1a\x18.todo.UpdateTodoResponse\x12?\n\nDeleteTodo\x12\x17.todo.DeleteTodoRequest\x1a\x18.todo.DeleteTodoResponse\x12<\n\tListTodos\x12\x16.todo.ListTodosRequest\x1a\x17.todo.ListTodosResponseB\x06Z\x04todob\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "proto.todo_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z\004todo"
    _TODO._serialized_start = 26
    _TODO._serialized_end = 77
    _CREATETODOREQUEST._serialized_start = 79
    _CREATETODOREQUEST._serialized_end = 131
    _CREATETODORESPONSE._serialized_start = 133
    _CREATETODORESPONSE._serialized_end = 179
    _READTODOREQUEST._serialized_start = 181
    _READTODOREQUEST._serialized_end = 210
    _READTODORESPONSE._serialized_start = 212
    _READTODORESPONSE._serialized_end = 256
    _UPDATETODOREQUEST._serialized_start = 258
    _UPDATETODOREQUEST._serialized_end = 322
    _UPDATETODORESPONSE._serialized_start = 324
    _UPDATETODORESPONSE._serialized_end = 370
    _DELETETODOREQUEST._serialized_start = 372
    _DELETETODOREQUEST._serialized_end = 403
    _DELETETODORESPONSE._serialized_start = 405
    _DELETETODORESPONSE._serialized_end = 442
    _LISTTODOSREQUEST._serialized_start = 444
    _LISTTODOSREQUEST._serialized_end = 462
    _LISTTODOSRESPONSE._serialized_start = 464
    _LISTTODOSRESPONSE._serialized_end = 510
    _TODOSERVICE._serialized_start = 513
    _TODOSERVICE._serialized_end = 842
# @@protoc_insertion_point(module_scope)
